# Generated by Django 4.1.2 on 2022-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("timeStamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
