# Generated by Django 4.1.2 on 2022-10-30 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_todo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 30, 11, 48, 6, 906477)),
        ),
    ]
