# Generated by Django 4.1.2 on 2022-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_todo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='timeStamp',
            field=models.DateTimeField(default='2022-30-10 12:09:05'),
        ),
    ]
